/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\Projects\Sanskar Portfolio v3\portfolio\public\game\models\porsche_911_turbo_s.glb -o D:\Projects\Sanskar Portfolio v3\portfolio\src\game\models\vehicle\Porsche.tsx --types 
Author: SeKali (https://sketchfab.com/zh.200.c)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-911-turbo-s-68d8ef218d7e42adbd4425dc43629705
Title: Porsche 911 Turbo S
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_89: THREE.Mesh
    Object_90: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_94: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_103: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_119: THREE.Mesh
    Object_120: THREE.Mesh
    Object_121: THREE.Mesh
    Object_123: THREE.Mesh
    Object_124: THREE.Mesh
    Object_125: THREE.Mesh
    Object_127: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_133: THREE.Mesh
    Object_134: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_167: THREE.Mesh
    Object_168: THREE.Mesh
    Object_169: THREE.Mesh
    Object_170: THREE.Mesh
    Object_171: THREE.Mesh
    Object_173: THREE.Mesh
    Object_175: THREE.Mesh
    Object_177: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_182: THREE.Mesh
    Object_184: THREE.Mesh
    Object_186: THREE.Mesh
    Object_188: THREE.Mesh
    Object_189: THREE.Mesh
    Object_190: THREE.Mesh
    Object_191: THREE.Mesh
    Object_192: THREE.Mesh
    Object_193: THREE.Mesh
    Object_195: THREE.Mesh
    Object_197: THREE.Mesh
    Object_199: THREE.Mesh
    Object_201: THREE.Mesh
    Object_202: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_208: THREE.Mesh
    Object_210: THREE.Mesh
    Object_212: THREE.Mesh
    Object_213: THREE.Mesh
    Object_214: THREE.Mesh
    Object_215: THREE.Mesh
    Object_216: THREE.Mesh
    Object_217: THREE.Mesh
    Object_219: THREE.Mesh
    Object_221: THREE.Mesh
    Object_223: THREE.Mesh
    Object_225: THREE.Mesh
    Object_226: THREE.Mesh
    Object_228: THREE.Mesh
    Object_230: THREE.Mesh
    Object_232: THREE.Mesh
    Object_233: THREE.Mesh
    Object_234: THREE.Mesh
    Object_235: THREE.Mesh
    Object_236: THREE.Mesh
    Object_237: THREE.Mesh
    Object_239: THREE.Mesh
    Object_241: THREE.Mesh
    Object_243: THREE.Mesh
    Object_245: THREE.Mesh
    Object_246: THREE.Mesh
    Object_248: THREE.Mesh
  }
  materials: {
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/game/porsche_911_turbo_s.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.018, 1.913, 2.247]} scale={0.618}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.024']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.027']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.013']} />
          </group>
          <group position={[0.018, 1.908, 2.247]} scale={0.618}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.024']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.009']} />
          </group>
          <group position={[0.018, 1.913, 2.247]} scale={0.618}>
            <mesh geometry={nodes.Object_21.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Object_22.geometry} material={materials['Material.012']} />
          </group>
          <group position={[0.018, 1.913, 2.247]} scale={0.618}>
            <mesh geometry={nodes.Object_24.geometry} material={materials['Material.024']} />
            <mesh geometry={nodes.Object_25.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_26.geometry} material={materials['Material.009']} />
          </group>
          <group position={[0.018, 1.913, 2.247]} scale={0.618}>
            <mesh geometry={nodes.Object_48.geometry} material={materials['Material.027']} />
            <mesh geometry={nodes.Object_49.geometry} material={materials['Material.026']} />
          </group>
          <group position={[0.018, 1.908, 2.247]} scale={0.618}>
            <mesh geometry={nodes.Object_77.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_78.geometry} material={materials['Material.022']} />
          </group>
          <group position={[0.023, 1.913, 2.247]} scale={0.618}>
            <mesh geometry={nodes.Object_88.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_89.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_90.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_91.geometry} material={materials['Material.023']} />
          </group>
          <group position={[1.48, 1.586, 2.769]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.081}>
            <mesh geometry={nodes.Object_93.geometry} material={materials['Material.021']} />
            <mesh geometry={nodes.Object_94.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Object_95.geometry} material={materials['Material.019']} />
          </group>
          <group position={[1.48, 1.586, 2.769]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.081}>
            <mesh geometry={nodes.Object_97.geometry} material={materials['Material.017']} />
            <mesh geometry={nodes.Object_98.geometry} material={materials['Material.016']} />
          </group>
          <group position={[1.48, 1.586, 2.769]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.081}>
            <mesh geometry={nodes.Object_102.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Object_103.geometry} material={materials['Material.014']} />
            <mesh geometry={nodes.Object_104.geometry} material={materials['Material.010']} />
          </group>
          <group position={[0.018, 1.913, 2.247]} scale={[-0.618, 0.618, 0.618]}>
            <mesh geometry={nodes.Object_118.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_119.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_120.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_121.geometry} material={materials['Material.023']} />
          </group>
          <group position={[-1.44, 1.586, 2.769]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.081, 0.081, 0.081]}>
            <mesh geometry={nodes.Object_123.geometry} material={materials['Material.021']} />
            <mesh geometry={nodes.Object_124.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Object_125.geometry} material={materials['Material.019']} />
          </group>
          <group position={[-1.44, 1.586, 2.769]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.081, 0.081, 0.081]}>
            <mesh geometry={nodes.Object_127.geometry} material={materials['Material.017']} />
            <mesh geometry={nodes.Object_128.geometry} material={materials['Material.016']} />
          </group>
          <group position={[-1.44, 1.586, 2.769]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.081, 0.081, 0.081]}>
            <mesh geometry={nodes.Object_132.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Object_133.geometry} material={materials['Material.014']} />
            <mesh geometry={nodes.Object_134.geometry} material={materials['Material.010']} />
          </group>
          <group position={[1.913, 0.872, 1.807]} rotation={[0.433, -0.007, -1.568]} scale={0.093}>
            <mesh geometry={nodes.Object_166.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_167.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_168.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_169.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_170.geometry} material={materials['Material.032']} />
            <mesh geometry={nodes.Object_171.geometry} material={materials['Material.031']} />
          </group>
          <group position={[1.735, 0.916, 1.51]} rotation={[-1.518, 0, -1.578]} scale={0.06}>
            <mesh geometry={nodes.Object_177.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_178.geometry} material={materials['Material.035']} />
          </group>
          <group position={[1.951, 0.899, -3.274]} rotation={[0.433, -0.007, -1.568]} scale={0.097}>
            <mesh geometry={nodes.Object_188.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_189.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_190.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_191.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_192.geometry} material={materials['Material.032']} />
            <mesh geometry={nodes.Object_193.geometry} material={materials['Material.031']} />
          </group>
          <group position={[1.765, 0.943, -3.583]} rotation={[-1.518, 0, -1.578]} scale={0.062}>
            <mesh geometry={nodes.Object_201.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_202.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-1.876, 0.872, 1.807]} rotation={[0.433, -0.007, 1.574]} scale={[-0.093, 0.093, 0.093]}>
            <mesh geometry={nodes.Object_212.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_213.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_214.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_215.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_216.geometry} material={materials['Material.032']} />
            <mesh geometry={nodes.Object_217.geometry} material={materials['Material.031']} />
          </group>
          <group position={[-1.698, 0.916, 1.51]} rotation={[-1.518, 0, 1.563]} scale={[-0.06, 0.06, 0.06]}>
            <mesh geometry={nodes.Object_225.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_226.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-1.928, 0.899, -3.274]} rotation={[0.433, -0.007, 1.574]} scale={[-0.097, 0.097, 0.097]}>
            <mesh geometry={nodes.Object_232.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_233.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_234.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_235.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Object_236.geometry} material={materials['Material.032']} />
            <mesh geometry={nodes.Object_237.geometry} material={materials['Material.031']} />
          </group>
          <group position={[-1.743, 0.943, -3.583]} rotation={[-1.518, 0, 1.563]} scale={[-0.062, 0.062, 0.062]}>
            <mesh geometry={nodes.Object_245.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_246.geometry} material={materials['Material.035']} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.024']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['Material.009']} position={[0.018, 1.908, 2.232]} scale={0.618} />
          <mesh geometry={nodes.Object_17.geometry} material={materials['Material.006']} position={[0.018, 1.908, 2.225]} scale={0.618} />
          <mesh geometry={nodes.Object_19.geometry} material={materials['Material.006']} position={[0.018, 1.908, 2.232]} scale={0.618} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['Material.009']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Material} position={[0.018, 1.746, -5.22]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.151} />
          <mesh geometry={nodes.Object_32.geometry} material={materials['Material.019']} position={[0.018, 1.746, -5.223]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.151} />
          <mesh geometry={nodes.Object_34.geometry} material={materials['Material.006']} position={[0.018, 1.913, 2.301]} scale={0.618} />
          <mesh geometry={nodes.Object_36.geometry} material={materials['Material.019']} position={[0.017, 1.913, 2.288]} scale={0.618} />
          <mesh geometry={nodes.Object_38.geometry} material={materials['Material.011']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['Material.029']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['Material.023']} position={[-0.02, 1.668, -5.248]} rotation={[1.627, 0, Math.PI]} scale={0.112} />
          <mesh geometry={nodes.Object_44.geometry} material={materials['Material.026']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_46.geometry} material={materials['Material.027']} position={[0.018, 1.908, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_51.geometry} material={materials['Material.027']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_53.geometry} material={materials['Material.009']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_55.geometry} material={materials['Material.026']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_57.geometry} material={materials['Material.006']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_59.geometry} material={materials['Material.027']} position={[0.018, 1.913, 2.238]} scale={0.618} />
          <mesh geometry={nodes.Object_61.geometry} material={materials['Material.028']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_63.geometry} material={materials['Material.024']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_65.geometry} material={materials['Material.024']} position={[0, 2.094, -5.116]} />
          <mesh geometry={nodes.Object_67.geometry} material={materials['Material.024']} position={[0.018, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_69.geometry} material={materials['Material.009']} position={[0, 0.778, 3.553]} />
          <mesh geometry={nodes.Object_71.geometry} material={materials['Material.009']} position={[0, 0.716, 3.407]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.317]} />
          <mesh geometry={nodes.Object_73.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Object_75.geometry} material={materials['Material.024']} position={[0, 0.039, 2.495]} scale={0.333} />
          <mesh geometry={nodes.Object_80.geometry} material={materials['Material.006']} position={[0, 1.664, 0]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials['Material.024']} position={[0, 1.664, 0.066]} />
          <mesh geometry={nodes.Object_84.geometry} material={materials['Material.024']} position={[0, 1.664, 0.066]} />
          <mesh geometry={nodes.Object_86.geometry} material={materials['Material.038']} position={[0, 1.664, 0.066]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials['Material.015']} position={[1.48, 1.586, 2.769]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.081} />
          <mesh geometry={nodes.Object_106.geometry} material={materials['Material.015']} position={[1.48, 1.569, 2.769]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-0.081, 0.081, 0.081]} />
          <mesh geometry={nodes.Object_108.geometry} material={materials['Material.022']} position={[0.023, 1.913, 2.247]} scale={0.618} />
          <mesh geometry={nodes.Object_110.geometry} material={materials['Material.005']} position={[1.48, 1.586, 2.769]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.081} />
          <mesh geometry={nodes.Object_112.geometry} material={materials['Material.005']} position={[1.48, 1.57, 2.769]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-0.081, 0.081, 0.081]} />
          <mesh geometry={nodes.Object_114.geometry} material={materials.material_0} position={[1.261, 1.493, 2.929]} rotation={[Math.PI / 2, 0.128, -Math.PI / 2]} scale={[0.024, 0.025, 0.025]} />
          <mesh geometry={nodes.Object_116.geometry} material={materials.material_0} position={[1.263, 1.481, 2.916]} rotation={[Math.PI / 2, 0.127, -Math.PI / 2]} scale={[0.019, 0.014, 0.014]} />
          <mesh geometry={nodes.Object_130.geometry} material={materials['Material.015']} position={[-1.44, 1.586, 2.769]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.081, 0.081, 0.081]} />
          <mesh geometry={nodes.Object_136.geometry} material={materials['Material.015']} position={[-1.44, 1.569, 2.769]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.081} />
          <mesh geometry={nodes.Object_138.geometry} material={materials['Material.022']} position={[0.018, 1.913, 2.247]} scale={[-0.618, 0.618, 0.618]} />
          <mesh geometry={nodes.Object_140.geometry} material={materials['Material.005']} position={[-1.44, 1.586, 2.769]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.081, 0.081, 0.081]} />
          <mesh geometry={nodes.Object_142.geometry} material={materials['Material.005']} position={[-1.44, 1.57, 2.769]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.081} />
          <mesh geometry={nodes.Object_144.geometry} material={materials.material_0} position={[-0.97, 1.195, 2.929]} rotation={[Math.PI / 2, 0.128, Math.PI / 2]} scale={[-0.024, 0.025, 0.025]} />
          <mesh geometry={nodes.Object_146.geometry} material={materials.material_0} position={[-0.972, 1.182, 2.916]} rotation={[Math.PI / 2, 0.127, Math.PI / 2]} scale={[-0.019, 0.014, 0.014]} />
          <mesh geometry={nodes.Object_148.geometry} material={materials['Material.053']} position={[0.015, 1.355, 3.541]} rotation={[0.456, 0, 0]} scale={0.06} />
          <mesh geometry={nodes.Object_150.geometry} material={materials['Material.008']} position={[0.207, 1.526, -5.211]} rotation={[0.87, Math.PI / 2, 0]} scale={0.147} />
          <mesh geometry={nodes.Object_152.geometry} material={materials['Material.004']} position={[0, 0.457, 0]} />
          <mesh geometry={nodes.Object_154.geometry} material={materials['Material.006']} position={[1.195, 0.953, 1.802]} rotation={[0, 0, -Math.PI / 2]} scale={[0.708, 0.566, 0.898]} />
          <mesh geometry={nodes.Object_156.geometry} material={materials['Material.006']} position={[-1.17, 0.953, 1.802]} rotation={[0, 0, -Math.PI / 2]} scale={[0.708, 0.566, 0.898]} />
          <mesh geometry={nodes.Object_158.geometry} material={materials['Material.006']} position={[1.245, 0.875, -3.398]} rotation={[0, 0, -Math.PI / 2]} scale={[0.74, 0.59, 0.987]} />
          <mesh geometry={nodes.Object_160.geometry} material={materials['Material.006']} position={[-1.22, 0.953, -3.398]} rotation={[0, 0, -Math.PI / 2]} scale={[0.74, 0.59, 0.987]} />
          <mesh geometry={nodes.Object_162.geometry} material={materials['Material.035']} position={[1.587, 0.872, 1.806]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.521} />
          <mesh geometry={nodes.Object_164.geometry} material={materials['Material.034']} position={[1.725, 0.875, 1.398]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.014} />
          <mesh geometry={nodes.Object_173.geometry} material={materials['Material.035']} position={[1.692, 0.87, 1.806]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.379} />
          <mesh geometry={nodes.Object_175.geometry} material={materials['Material.035']} position={[1.622, 0.87, 1.805]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.379} />
          <mesh geometry={nodes.Object_180.geometry} material={materials['Material.031']} position={[1.782, 0.913, 1.519]} rotation={[0.053, -0.007, -Math.PI / 2]} scale={0.035} />
          <mesh geometry={nodes.Object_182.geometry} material={materials['Material.036']} position={[1.904, 0.872, 1.807]} rotation={[0, 0, -Math.PI / 2]} scale={0.483} />
          <mesh geometry={nodes.Object_184.geometry} material={materials['Material.035']} position={[1.611, 0.898, -3.275]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.542} />
          <mesh geometry={nodes.Object_186.geometry} material={materials['Material.034']} position={[1.755, 0.901, -3.699]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.014} />
          <mesh geometry={nodes.Object_195.geometry} material={materials['Material.035']} position={[1.721, 0.896, -3.275]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.394} />
          <mesh geometry={nodes.Object_197.geometry} material={materials['Material.035']} position={[1.648, 0.896, -3.276]} rotation={[0, -0.007, -Math.PI / 2]} scale={0.394} />
          <mesh geometry={nodes.Object_199.geometry} material={materials['Material.036']} position={[1.942, 0.899, -3.274]} rotation={[0, 0, -Math.PI / 2]} scale={0.503} />
          <mesh geometry={nodes.Object_204.geometry} material={materials['Material.031']} position={[1.815, 0.941, -3.573]} rotation={[0.053, -0.007, -Math.PI / 2]} scale={0.036} />
          <mesh geometry={nodes.Object_206.geometry} material={materials['Material.034']} position={[-1.732, 0.901, -3.699]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.014, 0.014, 0.014]} />
          <mesh geometry={nodes.Object_208.geometry} material={materials['Material.035']} position={[-1.55, 0.872, 1.806]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.521, 0.521, 0.521]} />
          <mesh geometry={nodes.Object_210.geometry} material={materials['Material.034']} position={[-1.687, 0.875, 1.398]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.014, 0.014, 0.014]} />
          <mesh geometry={nodes.Object_219.geometry} material={materials['Material.035']} position={[-1.655, 0.87, 1.806]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.379, 0.379, 0.379]} />
          <mesh geometry={nodes.Object_221.geometry} material={materials['Material.035']} position={[-1.584, 0.87, 1.805]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.379, 0.379, 0.379]} />
          <mesh geometry={nodes.Object_223.geometry} material={materials['Material.036']} position={[-1.867, 0.872, 1.807]} rotation={[0, 0, Math.PI / 2]} scale={[-0.483, 0.483, 0.483]} />
          <mesh geometry={nodes.Object_228.geometry} material={materials['Material.031']} position={[-1.745, 0.913, 1.519]} rotation={[0.053, -0.007, Math.PI / 2]} scale={[-0.035, 0.035, 0.035]} />
          <mesh geometry={nodes.Object_230.geometry} material={materials['Material.035']} position={[-1.589, 0.898, -3.275]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.542, 0.542, 0.542]} />
          <mesh geometry={nodes.Object_239.geometry} material={materials['Material.035']} position={[-1.698, 0.896, -3.275]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.394, 0.394, 0.394]} />
          <mesh geometry={nodes.Object_241.geometry} material={materials['Material.035']} position={[-1.625, 0.896, -3.276]} rotation={[0, -0.007, Math.PI / 2]} scale={[-0.394, 0.394, 0.394]} />
          <mesh geometry={nodes.Object_243.geometry} material={materials['Material.036']} position={[-1.919, 0.899, -3.274]} rotation={[0, 0, Math.PI / 2]} scale={[-0.503, 0.503, 0.503]} />
          <mesh geometry={nodes.Object_248.geometry} material={materials['Material.031']} position={[-1.792, 0.941, -3.573]} rotation={[0.053, -0.007, Math.PI / 2]} scale={[-0.036, 0.036, 0.036]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/game/porsche_911_turbo_s.glb')
